config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :questions do
      resources :answers, only: [:new, :create]
    end
    collection do
      get 'search'
    end
    resources :time_managements, only: [:index, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :feedback

  with_options presence: true do
    validates :answer
    validates :feedback_id
  end

  validates :feedback_id, numericality: { other_than: 1, message: 'を選択してください' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '余裕でわかった' },
    { id: 3, name: '少し考えればわかった' },
    { id: 4, name: '難しかった' },
    { id: 5, name: '全然わからなかった' }
  ]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  with_options presence: true do
    validates :problem_statement
    validates :correct_answer
  end
end

app/models/time_management.rb
class TimeManagement < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :date
    validates :time
  end

  validate :date_cannot_be_in_the_past
  validates :time, numericality: { only_integer: true }

  def date_cannot_be_in_the_past
    errors.add(:date, 'は過去の日付にしないでください') if date.present? && date < Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  has_many :time_managements

  validates :nickname, { presence: true, uniqueness: true }

  def self.search(search)
    if search != ''
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
    @user = User.find(params[:user_id])
  end

  def create
    @question = Question.find(params[:question_id])
    @user = User.find(params[:user_id])
    @answer = Answer.new(answer_params)
    if @answer.valid?
      @answer.save
      redirect_to user_questions_path(@user.id, @question.id)
    else
      render :new
    end
  end

  private

  def answer_params
    params.permit(:answer, :feedback_id, :question_id).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :move_to_show, only: [:edit]

  def new
    @question = Question.new
    @user = User.find(params[:user_id])
  end

  def create
    @question = Question.new(question_params)
    if @question.valid?
      @question.save
      redirect_to user_path(current_user)
    else
      @user = User.find(params[:user_id])
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])
    @questions = Question.all.where(user_id: @user.id).page(params[:page]).per(7)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.where(user_id: current_user.id).page(params[:page]).per(5)
    @user = User.find(params[:user_id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @user = User.find(params[:user_id])
    if @question.update(question_update_params)
      redirect_to user_question_path(@user.id, @question.id)
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @user = User.find(params[:user_id])
    if Question.find(params[:id]).destroy
      redirect_to user_questions_path(@user.id, @question.id)
    else
      render 'show'
    end
  end

  private

  def question_params
    params.permit(:problem_statement, :correct_answer).merge(user_id: current_user.id)
  end

  def question_update_params
    params.require(:question).permit(:problem_statement, :correct_answer).merge(user_id: current_user.id)
  end

  def move_to_show
    @user = User.find(params[:user_id])
    redirect_to action: :show unless current_user.id == @user.id
  end
end

app/controllers/time_managements_controller.rb
class TimeManagementsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
  end

  def create
    data = params.keys[0]
    border = data.index(',')
    date = data.slice(0, border)
    length = data.length
    time = data.slice(border + 1, length - 1).to_i
    user_id = params[:user_id]
    if TimeManagement.exists?(date: date, user_id: user_id)
      time_management = TimeManagement.where(date: date, user_id: user_id)
      original_time = time_management[0][:time]
      addition_time = time + original_time
      time_management.update(time: addition_time)
    else
      TimeManagement.create(date: date, time: time, user_id: user_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('created_at DESC').page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @times = @user.time_managements.where(user_id: @user.id).page(params[:page]).per(10)
    @graph = []
    @times.each do |time|
      @graph << [time.date, time.time / 60]
    end
  end

  def search
    @users = User.search(params[:keyword]).all.order('created_at DESC').page(params[:page]).per(20)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/time_managements_helper.rb
module TimeManagementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/new.html.erb
<%= render "shared/header" %>
<div class="question-background">
  <div class="contents-row">
    <div class="container">
      <%= form_with url: user_question_answers_path(@user.id,@question.id), local: true do |f| %>
        <%= render 'shared/error_messages', model: @answer %>
        <h3 class="list-field">問題</h3>
        <div>
          <%= @question.problem_statement %>
        </div>
        <h3 class="list-field">解答</h3>
        <%= f.text_area :answer, placeholder:"解答文", class:"question-field", autofocus: true %>
        <div class="field", id="see_answer">
          <span class="answer-question-bottun">答えを見る</span>
        </div>
        <div class="hidden-answer", id="feedback">
          <div class="list-field">
            答え <%= @question.correct_answer %>
          </div>
          <div>
            問題の手応え
          </div>
          <div>
            <%= f.collection_select(:feedback_id, Feedback.all, :id, :name, {}, {class:"feedback-field"}) %>
          </div>
          <div class="new-answer-bottun">
            <%= f.submit "解答を保存する", class:"answer-question-bottun" %></div>
          </div>
        <div class="new-answer-bottun">
          <%= link_to "戻る", user_questions_path(@user.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/edit.html.erb
<%= render "shared/header" %>
<div class="question-background">
  <div class="contents-row">
    <div class="container">
      <%= form_with url: user_question_path(@user.id,@question.id), model: [@user,@question], method: :patch, local: true do |f| %>
      <%= render 'shared/error_messages', model: @question %>
        <h2 class="edit-question">問 題 編 集</h2>
        <h3 class="list-field">問題</h3>
        <%= f.text_area :problem_statement, placeholder:"問題文", class:"question-field", autofocus: true %>
        <h3 class="list-field">答え</h3>
        <%= f.text_area :correct_answer, placeholder:"答え", class:"question-field" %>
        <div class="edit-question-bottun">
          <%= f.submit "問題内容を更新", class:"update-question-bottun" %>
        </div>
        <div class="edit-question-bottun">
          <%= link_to "戻る", user_question_path(@user.id,@question.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<%= render "shared/header" %>

<div class="full-question-background">
  <div class="contents-row">
    <div class="index-container">
      <div class="index-container-box">
        <div class="index-user-name">
          <%= "#{@user.nickname}さん" %>
        </div>
        <h2 class="index-question">問 題 一 覧</h2>
        <% unless @questions.exists? %>
          問題を作成しておりません。
        <% end %>
        <% @questions.each do |question| %>
          <div class="list-field">
            <%= "問題 #{question.problem_statement}" %>
          </div>
          <div class="field">
            <%= link_to "詳細", user_question_path(@user.id,question.id), class:"index-question-bottun" %>
            <%= link_to "問題を解く", new_user_question_answer_path(@user.id,question.id), class:"index-question-bottun" %>
          </div>
        <% end %>
        <div class="center-question-bottun">
          <div>
            <%= paginate @questions %>
          </div>
          <div>
            <%= link_to "戻る", user_path(@user.id) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<%= render "shared/header" %>
<div class="question-background">
  <div class="contents-row">
    <div class="container">
      <%= form_with url: user_questions_path(@user.id), local: true do |f| %>
        <h2 class="new-question">問 題 作 成</h2>
        <%= render 'shared/error_messages', model: @question %>
        <h3 class="list-field">問題</h3>
          <%= f.text_area :problem_statement, placeholder:"問題文", class:"question-field", autofocus: true %>
        <h3 class="list-field">答え</h3>
          <%= f.text_area :correct_answer, placeholder:"答え", class:"question-field"%>
        <div class="new-question-bottun">
          <%= f.submit "問題作成", class:"create-question-bottun"%>
        </div>
        <div class="new-question-bottun">
          <%=  link_to "戻る", user_path(@user.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<%= render "shared/header" %>

<div class="full-question-background">
  <div class="contents-row">
    <div class="show-container">
      <div class="index-user-name">
        <%= "#{@user.nickname}さん" %>
      </div>
      <div>
        <h2 class="list-field">問題文</h2>
        <%= @question.problem_statement %>
        <h2 class="list-field">答え</h2>
        <%= @question.correct_answer %>
        <% if current_user.id == @question.user_id %>
          <div class="center-question-bottun">
            <div class="field">
              <%= link_to "問題を編集する", edit_user_question_path(@user.id,@question.id), class:"show-question-bottun" %>
            </div>
            <div id="confirm_deletion" class="field">
              <span class="show-question-bottun">問題を削除する</span>
            </div>
            <div class="hidden-confirmation", id="problem_delete">
              本当に削除しますか？
              <%= link_to "はい", user_question_path(@user.id,@question.id), method: :delete, class:"show-question-bottun" %>
              <span id="quit" class="show-question-bottun">いいえ</span>
            </div>
          </div>
        <% end %>
        <div class="center-question-bottun">
          <%= link_to "戻る", user_questions_path(@user.id) %>
        </div>
        <h2 class="list-field">今までの解答</h2>
        <% @answers.each do |answer| %>
          <div>
            <div class="field">
              <%= answer.answer %>
            </div>
            <div>
              <%= Feedback.find(answer.feedback_id).name %>
            </div>
          </div>
        <% end %>
        <%= paginate @answers %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="left-header">
    <div class="site-title">
      <%= link_to "Learning Efficiency", root_path, class:"title" %>
      <span class="title-explanation">効率的な勉強法</span>
    </div>
  </div>
  <div class="right-header">
    <ul class="devise-box">
      <% if user_signed_in? %>
        <li class="header-user-name"><%= "#{current_user.nickname}さん"%></li>
        <li ><%= link_to "マイページ", user_path(current_user.id), class:"devise" %></li>
        <li ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"devise"%></li>
      <% else %>
        <li ><%= link_to 'ログイン', user_session_path, class:"devise"%></li>
        <li ><%= link_to '新規登録', new_user_registration_path, class:"devise"%></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_login_header.html.erb
<header class="site-header">
  <div class="left-header">
    <div class="site-title">
      <%= link_to "Learning Efficiency", root_path, class:"title" %>
    </div>
  </div>
  <div class="right-header">
    <ul class="devise-box">
      <% if user_signed_in? %>
        <li ><%= link_to "マイページ", user_path(current_user.id), class:"devise" %></li>
        <li ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"devise"%></li>
      <% else %>
        <li ><%= link_to 'ログイン', user_session_path, class:"devise"%></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_signup_header.html.erb
<header class="site-header">
  <div class="left-header">
    <div class="site-title">
      <%= link_to "Learning Efficiency", root_path, class:"title" %>
    </div>
  </div>
  <div class="right-header">
    <ul class="devise-box">
      <% if user_signed_in? %>
        <li ><%= link_to "マイページ", user_path(current_user.id), class:"devise" %></li>
        <li ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"devise"%></li>
      <% else %>
        <li ><%= link_to '新規登録', new_user_registration_path, class:"devise"%></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/time_managements/index.html.erb
<%= render "shared/header" %>
<div class="timer">
  <div class="timer-box">
    <div class="caution">
      注意！ 0秒になった時に音がなります！
    </div>
    <div class="auto-timer-explanation">
      休憩用タイマーは勉強用タイマーが0秒になった時に自動で5分計測します。
    </div>
    <div>
      タイマーの時間は必要に応じて調整してください。
    </div>
    <div class="study-break-timer">
      <h3 class="timer-title">勉強用タイマー</h3>
      <form name="timer">
        <input type="number", id="min", name="min", class="timer-letter">分
        <input type="number", id="sec", name="sec", class="timer-letter">秒
        <div class="study-bottun">
          <input type="button", value="スタート", id="start", class="timer-bottun">
          <input type="button", value="ストップ", id="stop", class="hidden-timer-bottun">
          <input type="button", value="リセット", id="reset", class="hidden">
        </div>
      </form>
      <h3 class="timer-title">休憩用タイマー</h3>
      <form name="break_timer">
        <input type="number", id="break_min", name="break_min", class="timer-letter">分
        <input type="number", id="break_sec", name="break_sec", class="timer-letter">秒
        <div class="study-bottun">
          <input type="button", value="スタート", id="break_start", class="hidden-timer-bottun">
          <input type="button", value="ストップ", id="break_stop", class="timer-bottun">
          <input type="button", value="リセット", id="break_reset", class="hidden">
        </div>
      </form>
    </div>
  </div>
</div>

<audio controlslist="nodownload" id="sound", preload="auto", src="https://res.cloudinary.com/tetu/video/upload/v1598691645/Cell_Phone-Notification01-1_bcyosj.mp3"></audio>

<div id="user" class="hidden"> 
  <%= current_user.id %>
</div>

app/views/users/index.html.erb
<%= render "shared/header" %>

<div class="explanation">
  <div class="explanation-box">
    <div class="time-explanation">
      時間を区切って勉強することで集中力UP！
    </div>
    <div class="test-explanation">
      テスト形式で暗記することで勉強効率UP！
    </div>
    <div class="study-time-explanation">
      これまでの勉強時間を確認してやる気UP！
    </div>
  </div>
</div>
<div class="first-time">
  <div class="first-time-user">
    初めて利用する方へ
  </div>
  <div class="first-time-explanation">
    マイページをクリックして、タイマーをセットしてみよう！
  </div>
</div>

<h2 class="user-list">ユーザーリスト</h2>
<div class="user-list-explanation">
  ユーザー名をクリックすると、それぞれのユーザーページへ移動できます。
</div>
<%= form_with url: search_users_path, local: true, method: :get, class:"user-search-form" do |form| %>
  <%= form.text_field :keyword, placeholder: "ユーザーを検索する", class:"user-search-field" %>
  <%= form.submit "検索", class:"user-search-button" %>
<% end %>
<div class="user-list-background">
  <% @users.each do |user| %>
    <div class="user-name-box">
      <%= link_to "・#{user.nickname}", user_path(user.id), class:"user-name" %>
    </div>
  <% end %>
  <span class="paginate-users"><%= paginate @users %></span>
</div>

app/views/users/search.html.erb
<%= render "shared/header" %>


<h2 class="user-list">ユーザーリスト</h2>
<div class="user-list-explanation">
  ユーザー名をクリックすると、それぞれのユーザーページへ移動できます。
</div>
<%= form_with url: search_users_path, local: true, method: :get, class:"user-search-form" do |form| %>
  <%= form.text_field :keyword, placeholder: "ユーザーを検索する", class:"user-search-field" %>
  <%= form.submit "検索", class:"user-search-button" %>
<% end %>
<div class="user-list-background">
  <% @users.each do |user| %>
    <div class="user-name-box">
      <%= link_to "・#{user.nickname}", user_path(user.id), class:"user-name" %>
    </div>
  <% end %>
  <span class="paginate-users"><%= paginate @users %></span>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="show">
  <div class="show-background" >
    <div class="show-background-box">
      <span class="show-user-name"><%= "#{@user.nickname}さん" %></span>
      <% if current_user.id == @user.id %>
        <div class="link-sentence-box">
          <%= link_to "勉強時間管理タイマー", user_time_managements_path(@user.id), class:"link-sentence", target: :_blank %>
          <span class="link-timer-explanation">まずはタイマーセットから！</span>
        </div>
        <div class="link-sentence-box">
          <%= link_to "問題作成", new_user_question_path(@user.id), class:"link-sentence" %>
          <span class="link-question-create-explanation">覚えたいことを問題にしよう！</span>
        </div>
      <% end %>
      <div class="link-sentence-box">
        <%= link_to "作成した問題一覧", user_questions_path(@user.id), class:"link-sentence" %>
        <span class="link-question-index-explanation">作った問題を解いてみよう！</span>
      </div>
      <div class="link-sentence-box">
        <%= link_to "ユーザーリスト", root_path, class:"link-sentence" %>
        <span class="link-user-list-explanation">他のユーザーが作った問題を解いてみよう！</span>
      </div>
    </div>
  </div>

  <div class="study-time-box">
    <h2 class="show-study-time">勉強時間</h2>
    <div class="show-study-time-box">
      <div>
        勉強用タイマーで経過した時間が勉強時間として記録されます。
      </div>
      <div class="per-day-study-time">
        １日当たりの勉強時間（分）
      </div>
      <div class="study-time-graph">
        <%= line_chart @graph, height: "350px" %>
      </div>
      <% @times.each do |time| %>
        <div class="display-study-time">
          <%= time.date %>
            <% if time.time >= 3600 %>
              <%= "#{(time.time) / 3600}時間#{(time.time % 3600) / 60}分#{(time.time) % 60}秒" %></span>
            <% else %>
              <%= "#{(time.time % 3600) / 60}分#{(time.time) % 60}秒"%>
            <% end %>
        </div>
      <% end %>
      <%= paginate @times %>
    </div>
  </div>
</div>